version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: app-ai-agent-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_ai_agent
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  mongodb:
    image: mongo:6
    container_name: app-ai-agent-mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: app_ai_agent
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend-network

  minio:
    image: minio/minio
    container_name: app-ai-agent-minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
  mongodb_data:
  minio_data: 