"use client";

import { usePOA } from "@/hooks/use-poa";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { SectionTitle, AiEnhanceButton } from "./common-form-elements";
import { enhanceText } from "@/ai/flows/enhance-text";
import { generateIntroduction } from "@/ai/flows/generate-introduction";
import { defineScope } from "@/ai/flows/define-scope";
import { useState } from "react";
import { useToast } from "@/hooks/use-toast";
import { Sparkles, BookOpen, Target as ScopeIcon } from "lucide-react"; // Re-using Target as ScopeIcon

export function ProcedureDescriptionForm() {
  const { poa, updateField } = usePOA();
  const [isEnhancingText, setIsEnhancingText] = useState(false);
  const [isGeneratingIntro, setIsGeneratingIntro] = useState(false);
  const [isDefiningScope, setIsDefiningScope] = useState(false);
  const { toast } = useToast();

  const handleAiEnhance = async () => {
    if (!poa?.procedureDescription) return;
    setIsEnhancingText(true);
    try {
      const result = await enhanceText({ text: poa.procedureDescription });
      updateField("procedureDescription", result.enhancedText);
      toast({ title: "Procedure Description Enhanced", description: "The text has been improved by AI." });
    } catch (error) {
      console.error("Error enhancing procedure description:", error);
      toast({ title: "AI Enhancement Failed", description: "Could not enhance the text.", variant: "destructive" });
    }
    setIsEnhancingText(false);
  };

  const handleGenerateIntroduction = async () => {
    if (!poa?.procedureDescription) {
      toast({ title: "Missing Information", description: "Please provide a procedure description first.", variant: "destructive" });
      return;
    }
    setIsGeneratingIntro(true);
    try {
      const result = await generateIntroduction({ procedureDescription: poa.procedureDescription });
      updateField("introduction", result.introduction);
      toast({ title: "Introduction Generated", description: "An introduction has been generated by AI and added to the Introduction field (accessible via Scope section for now or a dedicated Intro section later)." });
    } catch (error) {
      console.error("Error generating introduction:", error);
      toast({ title: "Introduction Generation Failed", description: "Could not generate an introduction.", variant: "destructive" });
    }
    setIsGeneratingIntro(false);
  };

  const handleDefineScope = async () => {
    if (!poa?.procedureDescription) {
      toast({ title: "Missing Information", description: "Please provide a procedure description first.", variant: "destructive" });
      return;
    }
    setIsDefiningScope(true);
    try {
      const result = await defineScope({ procedureDescription: poa.procedureDescription });
      updateField("scope", result.scopeDefinition);
      toast({ title: "Scope Defined", description: "The scope has been defined by AI and added to the Scope field." });
    } catch (error) {
      console.error("Error defining scope:", error);
      toast({ title: "Scope Definition Failed", description: "Could not define the scope.", variant: "destructive" });
    }
    setIsDefiningScope(false);
  };
  
  if (!poa) return <div>Loading POA data...</div>;

  const procedureTextExists = !!poa.procedureDescription && poa.procedureDescription.length > 10;

  return (
    <Card className="shadow-lg">
      <CardHeader>
        <SectionTitle title="Procedure Description" description="Detail the overall procedure. This information can be used by AI to help generate other sections." />
      </CardHeader>
      <CardContent>
        <div className="space-y-2">
          <Label htmlFor="procedureDescription">Detailed Procedure</Label>
          <Textarea
            id="procedureDescription"
            value={poa.procedureDescription || ""}
            onChange={(e) => updateField("procedureDescription", e.target.value)}
            placeholder="Describe the step-by-step procedure, including any relevant context, involved parties, or systems..."
            rows={12}
            className="min-h-[250px]"
          />
        </div>
        <div className="mt-4 flex flex-wrap gap-2 justify-end">
          <AiEnhanceButton
            onClick={handleAiEnhance}
            isLoading={isEnhancingText}
            textExists={procedureTextExists}
          />
          <AiEnhanceButton
            onClick={handleGenerateIntroduction}
            isLoading={isGeneratingIntro}
            textExists={procedureTextExists}
            buttonText="Generate Introduction"
            disabled={!procedureTextExists || isGeneratingIntro}
            className="bg-primary/10 hover:bg-primary/20 text-primary border-primary/30"
          >
             <BookOpen className="mr-2 h-4 w-4" />
          </AiEnhanceButton>
           <AiEnhanceButton
            onClick={handleDefineScope}
            isLoading={isDefiningScope}
            textExists={procedureTextExists}
            buttonText="Define Scope"
            disabled={!procedureTextExists || isDefiningScope}
            className="bg-accent/10 hover:bg-accent/20 text-accent-foreground border-accent/30"
          >
            <ScopeIcon className="mr-2 h-4 w-4" />
          </AiEnhanceButton>
        </div>
         {poa.introduction && (
          <div className="mt-6 p-4 border rounded-md bg-secondary/50">
            <h4 className="font-semibold text-lg mb-2 text-primary">Generated Introduction Preview:</h4>
            <p className="text-sm text-foreground/90 whitespace-pre-wrap">{poa.introduction}</p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
